# Generated by Django 4.2.7 on 2023-11-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="update_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
