# Generated by Django 4.2.7 on 2023-11-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_update_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="description",
        ),
        migrations.RemoveField(
            model_name="task",
            name="is_done",
        ),
        migrations.AddField(
            model_name="task",
            name="descriptions",
            field=models.TextField(default="", max_length=200),
        ),
    ]
