# Generated by Django 4.2.7 on 2023-11-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_remove_task_description_remove_task_is_done_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="descriptions",
            new_name="description",
        ),
        migrations.AddField(
            model_name="task",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
