# Generated by Django 4.2.7 on 2023-11-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_rename_descriptions_task_description_task_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
