# Generated by Django 4.2.7 on 2023-11-23 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_alter_task_description_alter_task_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="description",
            new_name="notes",
        ),
    ]
